name: "Jest Code Coverage Commenter"
description: "Comments jest code coverage in a a pull request comment"
author: "Graham Plata"
branding:
  icon: "box"
  color: "white"
inputs:
  github-token:
    required: true
    description: "Github Token"
  test-command:
    required: false
    description: "Command to run the tests"
    default: "yarn run test --coverage"
  work-dir:
    required: false
    description: "Path to execute test-command"
  changed-since-master:
    required: false
    description: "Coverage of files changed since master"
  edit-pr-comment:
    required: false
    description: "Edit previous Pull Request comment"
runs:
  using: "node12"
  main: "dist/index.js"
