name: "Jest Code Coverage Commenter"
description: "Comments jest code coverage in a a pull request comment"
author: "Graham Plata"
branding:
  icon: "box"
  color: "white"
inputs:
  github-token:
    required: true
    description: "Github Token - ${{ secrets.GITHUB_TOKEN }}"
  test-command:
    required: false
    description: "Command to run the tests"
    default: "yarn run test --coverage"
runs:
  using: "node12"
  main: "dist/index.js"
